name       : openfx-misc
version    : 2.3.14
release    : 13
source     :
    - git|https://github.com/NatronGitHub/openfx-misc.git : Natron-2.3.14
license    : GPL-2.0-or-later
component  : multimedia.graphics
networking : yes
summary    : Miscellaneous OpenFX plugins
description: |
    Miscellaneous OpenFX plugins
builddeps  :
    - pkgconfig(gl)
build      : |
    %make CONFIG=release
install    : |
    %make_install \
        PLUGINPATH=/usr/share/OFX/Plugins \
        CONFIG=release
