name       : openfx-misc
version    : 2.1.9
release    : 1
source     :
    - https://github.com/MrKepzie/Natron/releases/download/2.1.9/openfx-misc-2.1.9.tar.xz : 110b64070de3e9a46b25aa8d4aeaf5950e3d6bd0ca04d9bf3a81014ab34c070a
license    : GPL-2.0
component  : multimedia.graphics
summary    : Miscellaneous OpenFX plugins
description: |
    Miscellaneous OpenFX plugins
networking : yes
builddeps  :
    - pkgconfig(gl)
build      : |
    %make CONFIG=release
install    : |
    %make_install \
        PLUGINPATH=/usr/share/OFX/Plugins \
        CONFIG=release