name       : openfx-misc
version    : 2.3.4
release    : 10
source     :
    - git|https://github.com/devernay/openfx-misc.git : Natron-2.3.4
license    : GPL-2.0
component  : multimedia.graphics
networking : yes
summary    : Miscellaneous OpenFX plugins
description: |
    Miscellaneous OpenFX plugins
builddeps  :
    - pkgconfig(gl)
build      : |
    %make CONFIG=release
install    : |
    %make_install \
        PLUGINPATH=/usr/share/OFX/Plugins \
        CONFIG=release
